(**** beginning of start.txt ****)
( NOTE: To start print, move platform to center      )
(       and place the nozzle just above the platform.)
(       It will move up  and extrude some plastic    )
(       that must be removed quickly.                )
(**** begin initilization commands ****)
G21 (set units to mm)
G90 (set positioning to absolute)
M106 (fan on)
M104 S<setting.temperature.baseTemperature> T0 (set extruder temperature)
M109 S<setting.chamber.bedTemperature> T0 (set heated-build-platform temperature)
(**** end initilization commands ****)
(**** begin homing ****)
G162 Y F2400.0 (Home up on Y)
G161 X Z F2400.0 (Home down on X and Z)
G92 X0 Y0 Z0 E0 (You are now at 0,0,0)
G1 X0.5 Y0.5 Z0.5 F10.0
G162 Y F10.0 (Home up on Y, slower)
G161 X Z F10.0 (Home down on X and Z, slower)
G92 X0 Y0 Z0 E0 (You are now at 0,0,0,0)
M132 X Y Z (Recall home positions for EEPROM)
;G1 X0 Y0 Z3 F4800.0 (Go to 0,0,0)
(**** end homing ****)
(**** begin pre-wipe commands ****)
M6 T0 (Wait for tool to heat up)
(**** end pre-wipe commands ****)
(**** end of start.txt ****)
